name: flutter_base_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/loading-II/flutter_base_core

environment:
  sdk: ">=2.19.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # http-dio
  dio: ^5.2.1
  dio_smart_retry: ^6.0.0
  dio_cookie_manager: ^3.1.1
  pretty_dio_logger: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

